---


- name: install tcl8.5
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - tcl8.5


- name: check file redis-stable
  stat: path=/opt/redis-stable
  register: check_redis
  tags:
    - redis

- name: unarchive redis
  become: yes
  unarchive: src=http://download.redis.io/redis-stable.tar.gz dest=/opt/ copy=no
  when: check_redis.stat.exists == false
  tags:
    - redis

- name: make
  become: yes
  become_user: root
  shell: chdir=/opt/redis-stable/src make
  shell: chdir=/opt/redis-stable/src make test
  shell: chdir=/opt/redis-stable/src make install


- name: copy config redis
  become: yes
  become_user: root
  copy: src=/opt/ansible/deploy/roles/redis/redis.conf dest=/etc/redis 
