---


- name: Install Nginx
  become: yes
  become_user: root
  apt: name=nginx state=latest
  tags:
    - nginx

- name: Copy file config
  become: yes
  copy: src=/opt/ansible/deploy/roles/nginx/nginx.conf/
        dest=/etc/nginx/sites-available/reverse.conf
  tags:
    - nginx


- stat: path=/etc/nginx/sites-enabled/
  register: st
  tags:
    - nginx-rm

- name: remove file default
  become: yes
  become_user: root
  when: st |changed
  shell: sudo rm /etc/nginx/sites-enabled/default/
  tags:
    - nginx-rm


- name: check file existed
  stat: path=/etc/nginx/sites-enabled/reverse.conf
  register: link
  tags:
    - nginx-ck

- name: create symbolic link
  become: yes
  become_user: root 
  shell: sudo ln -s /etc/nginx/sites-available/reverse.conf /etc/nginx/sites-enabled/
  when: link.stat.exists == false
  tags:
    - nginx-ck
