---


- name: Install Nginx
  become: yes
  become_user: root
  apt: name=nginx state=latest
  tags:
    - nginx


- name: copy file nginx.conf
  become: yes
  become_user: root
  copy: src=/opt/ansible/deploy/roles/nginx/nginx.conf
        dest=/etc/nginx/nginx.conf
  tags:
    - nginx


- name: restart nginx
  become: yes
  become_user: root
  service: name=nginx state=restarted
  tags:
    - nginx-rs
