---


- name: update
  become: yes
  become_user: root
  apt: update_cache=yes


- name: Install python-pip
  apt: name=python-pip state=installed
  become: yes
  become_user: root


- name: Install Flask
  apt: name=python-flask state=installed
  become: yes
  become_user: root
  tags:
     - flask

- name: Install python-redis
  become: yes
  become_user: root
  apt: name=python-redis state=installed


- name: copy bai4
  become: yes
  become_user: root
  copy: src=/opt/ansible/bai4.py dest=/opt/bai4.py 
